//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.11.14 at 03:10:59 PM EAT 
//


package com.sahay.cbs;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for liResponse complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="liResponse"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://vma.PHilae/}xiResponse"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="loanDetail" type="{http://vma.PHilae/}lnDetail" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "liResponse", propOrder = {
    "loanDetail"
})
public class LiResponse
    extends XiResponse
{

    protected LnDetail loanDetail;

    /**
     * Gets the value of the loanDetail property.
     * 
     * @return
     *     possible object is
     *     {@link LnDetail }
     *     
     */
    public LnDetail getLoanDetail() {
        return loanDetail;
    }

    /**
     * Sets the value of the loanDetail property.
     * 
     * @param value
     *     allowed object is
     *     {@link LnDetail }
     *     
     */
    public void setLoanDetail(LnDetail value) {
        this.loanDetail = value;
    }

}
