//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.11.14 at 03:10:59 PM EAT 
//


package com.sahay.cbs;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each
 * Java content interface and Java element interface
 * generated in the com.sahay.cbs package.
 * <p>An ObjectFactory allows you to programatically
 * construct new instances of the Java representation
 * for XML content. The Java representation of XML
 * content can consist of schema derived interfaces
 * and classes representing the binding of schema
 * type definitions, element declarations and model
 * groups.  Factory methods for each of these are
 * provided in this class.
 */
@XmlRegistry
public class ObjectFactory {


    private final static QName _CreateDepositAccountResponse_QNAME = new QName("http://vma.PHilae/", "createDepositAccountResponse");
    private final static QName _CreateDepositAccount_QNAME = new QName("http://vma.PHilae/", "createDepositAccount");
    private final static QName _CreateCustomer_QNAME = new QName("http://vma.PHilae/", "createCustomer");
    private final static QName _CreateCustomerResponse_QNAME = new QName("http://vma.PHilae/", "createCustomerResponse");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.sahay.cbs
     */
    public ObjectFactory() {
    }


    /**
     * Create an instance of {@link CcRequest }
     */
    public CcRequest createCcRequest() {
        return new CcRequest();
    }


    /**
     * Create an instance of {@link CreateDepositAccountResponse }
     */
    public CreateDepositAccountResponse createCreateDepositAccountResponse() {
        return new CreateDepositAccountResponse();
    }


    /**
     * Create an instance of {@link CreateDepositAccount }
     */
    public CreateDepositAccount createCreateDepositAccount() {
        return new CreateDepositAccount();
    }


    /**
     * Create an instance of {@link CreateCustomer }
     */
    public CreateCustomer createCreateCustomer() {
        return new CreateCustomer();
    }


    /**
     * Create an instance of {@link CreateCustomerResponse }
     */
    public CreateCustomerResponse createCreateCustomerResponse() {
        return new CreateCustomerResponse();
    }


    /**
     * Create an instance of {@link CaRequest }
     */
    public CaRequest createCaRequest() {
        return new CaRequest();
    }

    /**
     * Create an instance of {@link XiResponse }
     */
    public XiResponse createXiResponse() {
        return new XiResponse();
    }

    /**

     /**
     * Create an instance of {@link CqResult }
     */


    /**
     * Create an instance of {@link CaResponse }
     */
    public CaResponse createCaResponse() {
        return new CaResponse();
    }

    /**
     * Create an instance of {@link TxQuery }


     /**
     * Create an instance of {@link TpRequest }
     */

    /**
     * Create an instance of {@link CcIdentity }
     */
    public CcIdentity createCcIdentity() {
        return new CcIdentity();
    }


    public CcResponse createCcResponse() {
        return new CcResponse();
    }


    /**
     * Create an instance of {@link DhRequest }
     */


    /**
     * Create an instance of {@link FxResult }
     */


    /**
     * Create an instance of {@link CcContact }
     */
    public CcContact createCcContact() {
        return new CcContact();
    }


    @XmlElementDecl(namespace = "http://vma.PHilae/", name = "createDepositAccountResponse")
    public JAXBElement<CreateDepositAccountResponse> createCreateDepositAccountResponse(CreateDepositAccountResponse value) {
        return new JAXBElement<CreateDepositAccountResponse>(_CreateDepositAccountResponse_QNAME, CreateDepositAccountResponse.class, null, value);
    }


    @XmlElementDecl(namespace = "http://vma.PHilae/", name = "createDepositAccount")
    public JAXBElement<CreateDepositAccount> createCreateDepositAccount(CreateDepositAccount value) {
        return new JAXBElement<CreateDepositAccount>(_CreateDepositAccount_QNAME, CreateDepositAccount.class, null, value);
    }


    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CreateCustomer }{@code >}
     *
     * @param value Java instance representing xml element's value.
     * @return the new instance of {@link JAXBElement }{@code <}{@link CreateCustomer }{@code >}
     */
    @XmlElementDecl(namespace = "http://vma.PHilae/", name = "createCustomer")
    public JAXBElement<CreateCustomer> createCreateCustomer(CreateCustomer value) {
        return new JAXBElement<CreateCustomer>(_CreateCustomer_QNAME, CreateCustomer.class, null, value);
    }


    @XmlElementDecl(namespace = "http://vma.PHilae/", name = "createCustomerResponse")
    public JAXBElement<CreateCustomerResponse> createCreateCustomerResponse(CreateCustomerResponse value) {
        return new JAXBElement<CreateCustomerResponse>(_CreateCustomerResponse_QNAME, CreateCustomerResponse.class, null, value);
    }
}


