//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.01.18 at 03:25:16 PM EAT 
//


package com.sahay.cbs;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.sahay.cbs package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _GetAccountInformationResponse_QNAME = new QName("http://vma.PHilae/", "getAccountInformationResponse");
    private final static QName _GetAccountBalanceResponse_QNAME = new QName("http://vma.PHilae/", "getAccountBalanceResponse");
    private final static QName _GetUserDetailsResponse_QNAME = new QName("http://vma.PHilae/", "getUserDetailsResponse");
    private final static QName _QueryDepositAccountResponse_QNAME = new QName("http://vma.PHilae/", "queryDepositAccountResponse");
    private final static QName _GetCustomerInfoDetails_QNAME = new QName("http://vma.PHilae/", "getCustomerInfoDetails");
    private final static QName _PostDepositToGLTransferResponse_QNAME = new QName("http://vma.PHilae/", "postDepositToGLTransferResponse");
    private final static QName _GetBranchInfo_QNAME = new QName("http://vma.PHilae/", "getBranchInfo");
    private final static QName _GetCustomerAccountInfoDetailsResponse_QNAME = new QName("http://vma.PHilae/", "getCustomerAccountInfoDetailsResponse");
    private final static QName _PostGLToDepositTransferResponse_QNAME = new QName("http://vma.PHilae/", "postGLToDepositTransferResponse");
    private final static QName _ValidateUserResponse_QNAME = new QName("http://vma.PHilae/", "validateUserResponse");
    private final static QName _GetCustomerAccountInfoBasicResponse_QNAME = new QName("http://vma.PHilae/", "getCustomerAccountInfoBasicResponse");
    private final static QName _SearchCustomer_QNAME = new QName("http://vma.PHilae/", "searchCustomer");
    private final static QName _GetLoanScheduleInfo_QNAME = new QName("http://vma.PHilae/", "getLoanScheduleInfo");
    private final static QName _QueryLoanInformationResponse_QNAME = new QName("http://vma.PHilae/", "queryLoanInformationResponse");
    private final static QName _PostDepositTransfer_QNAME = new QName("http://vma.PHilae/", "postDepositTransfer");
    private final static QName _QueryCustomer_QNAME = new QName("http://vma.PHilae/", "queryCustomer");
    private final static QName _ActivateCustomerResponse_QNAME = new QName("http://vma.PHilae/", "activateCustomerResponse");
    private final static QName _GetCustomerInfoBasic_QNAME = new QName("http://vma.PHilae/", "getCustomerInfoBasic");
    private final static QName _GetBranchInfoResponse_QNAME = new QName("http://vma.PHilae/", "getBranchInfoResponse");
    private final static QName _PostDepositTransferResponse_QNAME = new QName("http://vma.PHilae/", "postDepositTransferResponse");
    private final static QName _QueryBranches_QNAME = new QName("http://vma.PHilae/", "queryBranches");
    private final static QName _GetInterestRate_QNAME = new QName("http://vma.PHilae/", "getInterestRate");
    private final static QName _QueryGLHistory_QNAME = new QName("http://vma.PHilae/", "queryGLHistory");
    private final static QName _SearchTransactionDetailsResponse_QNAME = new QName("http://vma.PHilae/", "searchTransactionDetailsResponse");
    private final static QName _GetForeignExchangeRateResponse_QNAME = new QName("http://vma.PHilae/", "getForeignExchangeRateResponse");
    private final static QName _QueryDepositAccount_QNAME = new QName("http://vma.PHilae/", "queryDepositAccount");
    private final static QName _QueryDepositHistoryResponse_QNAME = new QName("http://vma.PHilae/", "queryDepositHistoryResponse");
    private final static QName _QueryDepositBalanceResponse_QNAME = new QName("http://vma.PHilae/", "queryDepositBalanceResponse");
    private final static QName _GetAccountHistory_QNAME = new QName("http://vma.PHilae/", "getAccountHistory");
    private final static QName _CreateDepositAccountResponse_QNAME = new QName("http://vma.PHilae/", "createDepositAccountResponse");
    private final static QName _QueryLoanSchedule_QNAME = new QName("http://vma.PHilae/", "queryLoanSchedule");
    private final static QName _GetCustomerAccountInfoDetails_QNAME = new QName("http://vma.PHilae/", "getCustomerAccountInfoDetails");
    private final static QName _GetAccountBalance_QNAME = new QName("http://vma.PHilae/", "getAccountBalance");
    private final static QName _QueryLoanInformation_QNAME = new QName("http://vma.PHilae/", "queryLoanInformation");
    private final static QName _PostGLToDepositTransfer_QNAME = new QName("http://vma.PHilae/", "postGLToDepositTransfer");
    private final static QName _GetAccountHistoryResponse_QNAME = new QName("http://vma.PHilae/", "getAccountHistoryResponse");
    private final static QName _GetLoanInfo_QNAME = new QName("http://vma.PHilae/", "getLoanInfo");
    private final static QName _ActivateCustomer_QNAME = new QName("http://vma.PHilae/", "activateCustomer");
    private final static QName _PostGLToGLTransferResponse_QNAME = new QName("http://vma.PHilae/", "postGLToGLTransferResponse");
    private final static QName _QueryDepositMinistatementResponse_QNAME = new QName("http://vma.PHilae/", "queryDepositMinistatementResponse");
    private final static QName _ActivateDepositAccountResponse_QNAME = new QName("http://vma.PHilae/", "activateDepositAccountResponse");
    private final static QName _GetLoanInfoResponse_QNAME = new QName("http://vma.PHilae/", "getLoanInfoResponse");
    private final static QName _QueryGLHistoryResponse_QNAME = new QName("http://vma.PHilae/", "queryGLHistoryResponse");
    private final static QName _CreateDepositAccount_QNAME = new QName("http://vma.PHilae/", "createDepositAccount");
    private final static QName _SearchCustomerInBranchResponse_QNAME = new QName("http://vma.PHilae/", "searchCustomerInBranchResponse");
    private final static QName _QueryDepositBalance_QNAME = new QName("http://vma.PHilae/", "queryDepositBalance");
    private final static QName _QueryDepositHistory_QNAME = new QName("http://vma.PHilae/", "queryDepositHistory");
    private final static QName _ValidateTransaction_QNAME = new QName("http://vma.PHilae/", "validateTransaction");
    private final static QName _CreateCustomer_QNAME = new QName("http://vma.PHilae/", "createCustomer");
    private final static QName _GetCustomerInfoDetailsResponse_QNAME = new QName("http://vma.PHilae/", "getCustomerInfoDetailsResponse");
    private final static QName _QueryBranchesResponse_QNAME = new QName("http://vma.PHilae/", "queryBranchesResponse");
    private final static QName _CreateCustomerResponse_QNAME = new QName("http://vma.PHilae/", "createCustomerResponse");
    private final static QName _SearchTransactionDetails_QNAME = new QName("http://vma.PHilae/", "searchTransactionDetails");
    private final static QName _GetCustomerAccountInfoBasic_QNAME = new QName("http://vma.PHilae/", "getCustomerAccountInfoBasic");
    private final static QName _QueryDepositMinistatement_QNAME = new QName("http://vma.PHilae/", "queryDepositMinistatement");
    private final static QName _ActivateDepositAccount_QNAME = new QName("http://vma.PHilae/", "activateDepositAccount");
    private final static QName _SearchCustomerResponse_QNAME = new QName("http://vma.PHilae/", "searchCustomerResponse");
    private final static QName _GetCustomerInfoBasicResponse_QNAME = new QName("http://vma.PHilae/", "getCustomerInfoBasicResponse");
    private final static QName _GetInterestRateResponse_QNAME = new QName("http://vma.PHilae/", "getInterestRateResponse");
    private final static QName _GetForeignExchangeRate_QNAME = new QName("http://vma.PHilae/", "getForeignExchangeRate");
    private final static QName _GetUserDetails_QNAME = new QName("http://vma.PHilae/", "getUserDetails");
    private final static QName _PostDepositToGLTransfer_QNAME = new QName("http://vma.PHilae/", "postDepositToGLTransfer");
    private final static QName _QueryCustomerResponse_QNAME = new QName("http://vma.PHilae/", "queryCustomerResponse");
    private final static QName _ValidateTransactionResponse_QNAME = new QName("http://vma.PHilae/", "validateTransactionResponse");
    private final static QName _ValidateUser_QNAME = new QName("http://vma.PHilae/", "validateUser");
    private final static QName _QueryLoanScheduleResponse_QNAME = new QName("http://vma.PHilae/", "queryLoanScheduleResponse");
    private final static QName _PostGLToGLTransfer_QNAME = new QName("http://vma.PHilae/", "postGLToGLTransfer");
    private final static QName _GetAccountInformation_QNAME = new QName("http://vma.PHilae/", "getAccountInformation");
    private final static QName _SearchCustomerInBranch_QNAME = new QName("http://vma.PHilae/", "searchCustomerInBranch");
    private final static QName _GetLoanScheduleInfoResponse_QNAME = new QName("http://vma.PHilae/", "getLoanScheduleInfoResponse");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.sahay.cbs
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link DhResponse }
     * 
     */
    public DhResponse createDhResponse() {
        return new DhResponse();
    }

    /**
     * Create an instance of {@link LsResponse }
     * 
     */
    public LsResponse createLsResponse() {
        return new LsResponse();
    }

    /**
     * Create an instance of {@link BrResponse }
     * 
     */
    public BrResponse createBrResponse() {
        return new BrResponse();
    }

    /**
     * Create an instance of {@link LhResponse }
     * 
     */
    public LhResponse createLhResponse() {
        return new LhResponse();
    }

    /**
     * Create an instance of {@link CcRequest }
     * 
     */
    public CcRequest createCcRequest() {
        return new CcRequest();
    }

    /**
     * Create an instance of {@link GetAccountInformationResponse }
     * 
     */
    public GetAccountInformationResponse createGetAccountInformationResponse() {
        return new GetAccountInformationResponse();
    }

    /**
     * Create an instance of {@link GetAccountBalanceResponse }
     * 
     */
    public GetAccountBalanceResponse createGetAccountBalanceResponse() {
        return new GetAccountBalanceResponse();
    }

    /**
     * Create an instance of {@link GetUserDetailsResponse }
     * 
     */
    public GetUserDetailsResponse createGetUserDetailsResponse() {
        return new GetUserDetailsResponse();
    }

    /**
     * Create an instance of {@link QueryDepositAccountResponse }
     * 
     */
    public QueryDepositAccountResponse createQueryDepositAccountResponse() {
        return new QueryDepositAccountResponse();
    }

    /**
     * Create an instance of {@link GetCustomerInfoDetails }
     * 
     */
    public GetCustomerInfoDetails createGetCustomerInfoDetails() {
        return new GetCustomerInfoDetails();
    }

    /**
     * Create an instance of {@link PostDepositToGLTransferResponse }
     * 
     */
    public PostDepositToGLTransferResponse createPostDepositToGLTransferResponse() {
        return new PostDepositToGLTransferResponse();
    }

    /**
     * Create an instance of {@link GetBranchInfo }
     * 
     */
    public GetBranchInfo createGetBranchInfo() {
        return new GetBranchInfo();
    }

    /**
     * Create an instance of {@link GetCustomerAccountInfoDetailsResponse }
     * 
     */
    public GetCustomerAccountInfoDetailsResponse createGetCustomerAccountInfoDetailsResponse() {
        return new GetCustomerAccountInfoDetailsResponse();
    }

    /**
     * Create an instance of {@link PostGLToDepositTransferResponse }
     * 
     */
    public PostGLToDepositTransferResponse createPostGLToDepositTransferResponse() {
        return new PostGLToDepositTransferResponse();
    }

    /**
     * Create an instance of {@link ValidateUserResponse }
     * 
     */
    public ValidateUserResponse createValidateUserResponse() {
        return new ValidateUserResponse();
    }

    /**
     * Create an instance of {@link GetCustomerAccountInfoBasicResponse }
     * 
     */
    public GetCustomerAccountInfoBasicResponse createGetCustomerAccountInfoBasicResponse() {
        return new GetCustomerAccountInfoBasicResponse();
    }

    /**
     * Create an instance of {@link SearchCustomer }
     * 
     */
    public SearchCustomer createSearchCustomer() {
        return new SearchCustomer();
    }

    /**
     * Create an instance of {@link GetLoanScheduleInfo }
     * 
     */
    public GetLoanScheduleInfo createGetLoanScheduleInfo() {
        return new GetLoanScheduleInfo();
    }

    /**
     * Create an instance of {@link QueryLoanInformationResponse }
     * 
     */
    public QueryLoanInformationResponse createQueryLoanInformationResponse() {
        return new QueryLoanInformationResponse();
    }

    /**
     * Create an instance of {@link PostDepositTransfer }
     * 
     */
    public PostDepositTransfer createPostDepositTransfer() {
        return new PostDepositTransfer();
    }

    /**
     * Create an instance of {@link QueryCustomer }
     * 
     */
    public QueryCustomer createQueryCustomer() {
        return new QueryCustomer();
    }

    /**
     * Create an instance of {@link ActivateCustomerResponse }
     * 
     */
    public ActivateCustomerResponse createActivateCustomerResponse() {
        return new ActivateCustomerResponse();
    }

    /**
     * Create an instance of {@link GetCustomerInfoBasic }
     * 
     */
    public GetCustomerInfoBasic createGetCustomerInfoBasic() {
        return new GetCustomerInfoBasic();
    }

    /**
     * Create an instance of {@link GetBranchInfoResponse }
     * 
     */
    public GetBranchInfoResponse createGetBranchInfoResponse() {
        return new GetBranchInfoResponse();
    }

    /**
     * Create an instance of {@link PostDepositTransferResponse }
     * 
     */
    public PostDepositTransferResponse createPostDepositTransferResponse() {
        return new PostDepositTransferResponse();
    }

    /**
     * Create an instance of {@link QueryBranches }
     * 
     */
    public QueryBranches createQueryBranches() {
        return new QueryBranches();
    }

    /**
     * Create an instance of {@link GetInterestRate }
     * 
     */
    public GetInterestRate createGetInterestRate() {
        return new GetInterestRate();
    }

    /**
     * Create an instance of {@link QueryGLHistory }
     * 
     */
    public QueryGLHistory createQueryGLHistory() {
        return new QueryGLHistory();
    }

    /**
     * Create an instance of {@link SearchTransactionDetailsResponse }
     * 
     */
    public SearchTransactionDetailsResponse createSearchTransactionDetailsResponse() {
        return new SearchTransactionDetailsResponse();
    }

    /**
     * Create an instance of {@link GetForeignExchangeRateResponse }
     * 
     */
    public GetForeignExchangeRateResponse createGetForeignExchangeRateResponse() {
        return new GetForeignExchangeRateResponse();
    }

    /**
     * Create an instance of {@link QueryDepositAccount }
     * 
     */
    public QueryDepositAccount createQueryDepositAccount() {
        return new QueryDepositAccount();
    }

    /**
     * Create an instance of {@link QueryDepositHistoryResponse }
     * 
     */
    public QueryDepositHistoryResponse createQueryDepositHistoryResponse() {
        return new QueryDepositHistoryResponse();
    }

    /**
     * Create an instance of {@link QueryDepositBalanceResponse }
     * 
     */
    public QueryDepositBalanceResponse createQueryDepositBalanceResponse() {
        return new QueryDepositBalanceResponse();
    }

    /**
     * Create an instance of {@link GetAccountHistory }
     * 
     */
    public GetAccountHistory createGetAccountHistory() {
        return new GetAccountHistory();
    }

    /**
     * Create an instance of {@link CreateDepositAccountResponse }
     * 
     */
    public CreateDepositAccountResponse createCreateDepositAccountResponse() {
        return new CreateDepositAccountResponse();
    }

    /**
     * Create an instance of {@link QueryLoanSchedule }
     * 
     */
    public QueryLoanSchedule createQueryLoanSchedule() {
        return new QueryLoanSchedule();
    }

    /**
     * Create an instance of {@link GetCustomerAccountInfoDetails }
     * 
     */
    public GetCustomerAccountInfoDetails createGetCustomerAccountInfoDetails() {
        return new GetCustomerAccountInfoDetails();
    }

    /**
     * Create an instance of {@link GetAccountBalance }
     * 
     */
    public GetAccountBalance createGetAccountBalance() {
        return new GetAccountBalance();
    }

    /**
     * Create an instance of {@link QueryLoanInformation }
     * 
     */
    public QueryLoanInformation createQueryLoanInformation() {
        return new QueryLoanInformation();
    }

    /**
     * Create an instance of {@link PostGLToDepositTransfer }
     * 
     */
    public PostGLToDepositTransfer createPostGLToDepositTransfer() {
        return new PostGLToDepositTransfer();
    }

    /**
     * Create an instance of {@link GetAccountHistoryResponse }
     * 
     */
    public GetAccountHistoryResponse createGetAccountHistoryResponse() {
        return new GetAccountHistoryResponse();
    }

    /**
     * Create an instance of {@link GetLoanInfo }
     * 
     */
    public GetLoanInfo createGetLoanInfo() {
        return new GetLoanInfo();
    }

    /**
     * Create an instance of {@link ActivateCustomer }
     * 
     */
    public ActivateCustomer createActivateCustomer() {
        return new ActivateCustomer();
    }

    /**
     * Create an instance of {@link PostGLToGLTransferResponse }
     * 
     */
    public PostGLToGLTransferResponse createPostGLToGLTransferResponse() {
        return new PostGLToGLTransferResponse();
    }

    /**
     * Create an instance of {@link QueryDepositMinistatementResponse }
     * 
     */
    public QueryDepositMinistatementResponse createQueryDepositMinistatementResponse() {
        return new QueryDepositMinistatementResponse();
    }

    /**
     * Create an instance of {@link ActivateDepositAccountResponse }
     * 
     */
    public ActivateDepositAccountResponse createActivateDepositAccountResponse() {
        return new ActivateDepositAccountResponse();
    }

    /**
     * Create an instance of {@link GetLoanInfoResponse }
     * 
     */
    public GetLoanInfoResponse createGetLoanInfoResponse() {
        return new GetLoanInfoResponse();
    }

    /**
     * Create an instance of {@link QueryGLHistoryResponse }
     * 
     */
    public QueryGLHistoryResponse createQueryGLHistoryResponse() {
        return new QueryGLHistoryResponse();
    }

    /**
     * Create an instance of {@link CreateDepositAccount }
     * 
     */
    public CreateDepositAccount createCreateDepositAccount() {
        return new CreateDepositAccount();
    }

    /**
     * Create an instance of {@link SearchCustomerInBranchResponse }
     * 
     */
    public SearchCustomerInBranchResponse createSearchCustomerInBranchResponse() {
        return new SearchCustomerInBranchResponse();
    }

    /**
     * Create an instance of {@link QueryDepositBalance }
     * 
     */
    public QueryDepositBalance createQueryDepositBalance() {
        return new QueryDepositBalance();
    }

    /**
     * Create an instance of {@link QueryDepositHistory }
     * 
     */
    public QueryDepositHistory createQueryDepositHistory() {
        return new QueryDepositHistory();
    }

    /**
     * Create an instance of {@link ValidateTransaction }
     * 
     */
    public ValidateTransaction createValidateTransaction() {
        return new ValidateTransaction();
    }

    /**
     * Create an instance of {@link CreateCustomer }
     * 
     */
    public CreateCustomer createCreateCustomer() {
        return new CreateCustomer();
    }

    /**
     * Create an instance of {@link GetCustomerInfoDetailsResponse }
     * 
     */
    public GetCustomerInfoDetailsResponse createGetCustomerInfoDetailsResponse() {
        return new GetCustomerInfoDetailsResponse();
    }

    /**
     * Create an instance of {@link QueryBranchesResponse }
     * 
     */
    public QueryBranchesResponse createQueryBranchesResponse() {
        return new QueryBranchesResponse();
    }

    /**
     * Create an instance of {@link CreateCustomerResponse }
     * 
     */
    public CreateCustomerResponse createCreateCustomerResponse() {
        return new CreateCustomerResponse();
    }

    /**
     * Create an instance of {@link SearchTransactionDetails }
     * 
     */
    public SearchTransactionDetails createSearchTransactionDetails() {
        return new SearchTransactionDetails();
    }

    /**
     * Create an instance of {@link GetCustomerAccountInfoBasic }
     * 
     */
    public GetCustomerAccountInfoBasic createGetCustomerAccountInfoBasic() {
        return new GetCustomerAccountInfoBasic();
    }

    /**
     * Create an instance of {@link QueryDepositMinistatement }
     * 
     */
    public QueryDepositMinistatement createQueryDepositMinistatement() {
        return new QueryDepositMinistatement();
    }

    /**
     * Create an instance of {@link ActivateDepositAccount }
     * 
     */
    public ActivateDepositAccount createActivateDepositAccount() {
        return new ActivateDepositAccount();
    }

    /**
     * Create an instance of {@link SearchCustomerResponse }
     * 
     */
    public SearchCustomerResponse createSearchCustomerResponse() {
        return new SearchCustomerResponse();
    }

    /**
     * Create an instance of {@link GetCustomerInfoBasicResponse }
     * 
     */
    public GetCustomerInfoBasicResponse createGetCustomerInfoBasicResponse() {
        return new GetCustomerInfoBasicResponse();
    }

    /**
     * Create an instance of {@link GetInterestRateResponse }
     * 
     */
    public GetInterestRateResponse createGetInterestRateResponse() {
        return new GetInterestRateResponse();
    }

    /**
     * Create an instance of {@link GetForeignExchangeRate }
     * 
     */
    public GetForeignExchangeRate createGetForeignExchangeRate() {
        return new GetForeignExchangeRate();
    }

    /**
     * Create an instance of {@link GetUserDetails }
     * 
     */
    public GetUserDetails createGetUserDetails() {
        return new GetUserDetails();
    }

    /**
     * Create an instance of {@link PostDepositToGLTransfer }
     * 
     */
    public PostDepositToGLTransfer createPostDepositToGLTransfer() {
        return new PostDepositToGLTransfer();
    }

    /**
     * Create an instance of {@link QueryCustomerResponse }
     * 
     */
    public QueryCustomerResponse createQueryCustomerResponse() {
        return new QueryCustomerResponse();
    }

    /**
     * Create an instance of {@link ValidateTransactionResponse }
     * 
     */
    public ValidateTransactionResponse createValidateTransactionResponse() {
        return new ValidateTransactionResponse();
    }

    /**
     * Create an instance of {@link ValidateUser }
     * 
     */
    public ValidateUser createValidateUser() {
        return new ValidateUser();
    }

    /**
     * Create an instance of {@link QueryLoanScheduleResponse }
     * 
     */
    public QueryLoanScheduleResponse createQueryLoanScheduleResponse() {
        return new QueryLoanScheduleResponse();
    }

    /**
     * Create an instance of {@link PostGLToGLTransfer }
     * 
     */
    public PostGLToGLTransfer createPostGLToGLTransfer() {
        return new PostGLToGLTransfer();
    }

    /**
     * Create an instance of {@link GetAccountInformation }
     * 
     */
    public GetAccountInformation createGetAccountInformation() {
        return new GetAccountInformation();
    }

    /**
     * Create an instance of {@link SearchCustomerInBranch }
     * 
     */
    public SearchCustomerInBranch createSearchCustomerInBranch() {
        return new SearchCustomerInBranch();
    }

    /**
     * Create an instance of {@link GetLoanScheduleInfoResponse }
     * 
     */
    public GetLoanScheduleInfoResponse createGetLoanScheduleInfoResponse() {
        return new GetLoanScheduleInfoResponse();
    }

    /**
     * Create an instance of {@link CaRequest }
     * 
     */
    public CaRequest createCaRequest() {
        return new CaRequest();
    }

    /**
     * Create an instance of {@link FxRate }
     * 
     */
    public FxRate createFxRate() {
        return new FxRate();
    }

    /**
     * Create an instance of {@link CnAccount }
     * 
     */
    public CnAccount createCnAccount() {
        return new CnAccount();
    }

    /**
     * Create an instance of {@link ClResult }
     * 
     */
    public ClResult createClResult() {
        return new ClResult();
    }

    /**
     * Create an instance of {@link UsRole }
     * 
     */
    public UsRole createUsRole() {
        return new UsRole();
    }

    /**
     * Create an instance of {@link AcQuery }
     * 
     */
    public AcQuery createAcQuery() {
        return new AcQuery();
    }

    /**
     * Create an instance of {@link CuQuery }
     * 
     */
    public CuQuery createCuQuery() {
        return new CuQuery();
    }

    /**
     * Create an instance of {@link CbTxn }
     * 
     */
    public CbTxn createCbTxn() {
        return new CbTxn();
    }

    /**
     * Create an instance of {@link TlDrawer }
     * 
     */
    public TlDrawer createTlDrawer() {
        return new TlDrawer();
    }

    /**
     * Create an instance of {@link UlRequest }
     * 
     */
    public UlRequest createUlRequest() {
        return new UlRequest();
    }

    /**
     * Create an instance of {@link FxQuery }
     * 
     */
    public FxQuery createFxQuery() {
        return new FxQuery();
    }

    /**
     * Create an instance of {@link UrLimit }
     * 
     */
    public UrLimit createUrLimit() {
        return new UrLimit();
    }

    /**
     * Create an instance of {@link LiResponse }
     * 
     */
    public LiResponse createLiResponse() {
        return new LiResponse();
    }

    /**
     * Create an instance of {@link XiResponse }
     * 
     */
    public XiResponse createXiResponse() {
        return new XiResponse();
    }

    /**
     * Create an instance of {@link BnUser }
     * 
     */
    public BnUser createBnUser() {
        return new BnUser();
    }

    /**
     * Create an instance of {@link CqResult }
     * 
     */
    public CqResult createCqResult() {
        return new CqResult();
    }

    /**
     * Create an instance of {@link CaResponse }
     * 
     */
    public CaResponse createCaResponse() {
        return new CaResponse();
    }

    /**
     * Create an instance of {@link TxQuery }
     * 
     */
    public TxQuery createTxQuery() {
        return new TxQuery();
    }

    /**
     * Create an instance of {@link CnCurrency }
     * 
     */
    public CnCurrency createCnCurrency() {
        return new CnCurrency();
    }

    /**
     * Create an instance of {@link PiRate }
     * 
     */
    public PiRate createPiRate() {
        return new PiRate();
    }

    /**
     * Create an instance of {@link TxRequest }
     * 
     */
    public TxRequest createTxRequest() {
        return new TxRequest();
    }

    /**
     * Create an instance of {@link TpRequest }
     * 
     */
    public TpRequest createTpRequest() {
        return new TpRequest();
    }

    /**
     * Create an instance of {@link LhRequest }
     * 
     */
    public LhRequest createLhRequest() {
        return new LhRequest();
    }

    /**
     * Create an instance of {@link CcIdentity }
     * 
     */
    public CcIdentity createCcIdentity() {
        return new CcIdentity();
    }

    /**
     * Create an instance of {@link TqResult }
     * 
     */
    public TqResult createTqResult() {
        return new TqResult();
    }

    /**
     * Create an instance of {@link CnCustomer }
     * 
     */
    public CnCustomer createCnCustomer() {
        return new CnCustomer();
    }

    /**
     * Create an instance of {@link XiRequest }
     * 
     */
    public XiRequest createXiRequest() {
        return new XiRequest();
    }

    /**
     * Create an instance of {@link CcResponse }
     * 
     */
    public CcResponse createCcResponse() {
        return new CcResponse();
    }

    /**
     * Create an instance of {@link LnDetail }
     * 
     */
    public LnDetail createLnDetail() {
        return new LnDetail();
    }

    /**
     * Create an instance of {@link AqResult }
     * 
     */
    public AqResult createAqResult() {
        return new AqResult();
    }

    /**
     * Create an instance of {@link PiResult }
     * 
     */
    public PiResult createPiResult() {
        return new PiResult();
    }

    /**
     * Create an instance of {@link DhRequest }
     * 
     */
    public DhRequest createDhRequest() {
        return new DhRequest();
    }

    /**
     * Create an instance of {@link FxResult }
     * 
     */
    public FxResult createFxResult() {
        return new FxResult();
    }

    /**
     * Create an instance of {@link CcContact }
     * 
     */
    public CcContact createCcContact() {
        return new CcContact();
    }

    /**
     * Create an instance of {@link DhRecord }
     * 
     */
    public DhRecord createDhRecord() {
        return new DhRecord();
    }

    /**
     * Create an instance of {@link PiQuery }
     * 
     */
    public PiQuery createPiQuery() {
        return new PiQuery();
    }

    /**
     * Create an instance of {@link LhRecord }
     * 
     */
    public LhRecord createLhRecord() {
        return new LhRecord();
    }

    /**
     * Create an instance of {@link ClQuery }
     * 
     */
    public ClQuery createClQuery() {
        return new ClQuery();
    }

    /**
     * Create an instance of {@link LnEvent }
     * 
     */
    public LnEvent createLnEvent() {
        return new LnEvent();
    }

    /**
     * Create an instance of {@link CcImage }
     * 
     */
    public CcImage createCcImage() {
        return new CcImage();
    }

    /**
     * Create an instance of {@link CnBranch }
     * 
     */
    public CnBranch createCnBranch() {
        return new CnBranch();
    }

    /**
     * Create an instance of {@link UlResponse }
     * 
     */
    public UlResponse createUlResponse() {
        return new UlResponse();
    }

    /**
     * Create an instance of {@link DhResponse.Records }
     * 
     */
    public DhResponse.Records createDhResponseRecords() {
        return new DhResponse.Records();
    }

    /**
     * Create an instance of {@link LsResponse.Events }
     * 
     */
    public LsResponse.Events createLsResponseEvents() {
        return new LsResponse.Events();
    }

    /**
     * Create an instance of {@link BrResponse.Branches }
     * 
     */
    public BrResponse.Branches createBrResponseBranches() {
        return new BrResponse.Branches();
    }

    /**
     * Create an instance of {@link LhResponse.Records }
     * 
     */
    public LhResponse.Records createLhResponseRecords() {
        return new LhResponse.Records();
    }

    /**
     * Create an instance of {@link CcRequest.Identities }
     * 
     */
    public CcRequest.Identities createCcRequestIdentities() {
        return new CcRequest.Identities();
    }

    /**
     * Create an instance of {@link CcRequest.Contacts }
     * 
     */
    public CcRequest.Contacts createCcRequestContacts() {
        return new CcRequest.Contacts();
    }

    /**
     * Create an instance of {@link CcRequest.Images }
     * 
     */
    public CcRequest.Images createCcRequestImages() {
        return new CcRequest.Images();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetAccountInformationResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link GetAccountInformationResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://vma.PHilae/", name = "getAccountInformationResponse")
    public JAXBElement<GetAccountInformationResponse> createGetAccountInformationResponse(GetAccountInformationResponse value) {
        return new JAXBElement<GetAccountInformationResponse>(_GetAccountInformationResponse_QNAME, GetAccountInformationResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetAccountBalanceResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link GetAccountBalanceResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://vma.PHilae/", name = "getAccountBalanceResponse")
    public JAXBElement<GetAccountBalanceResponse> createGetAccountBalanceResponse(GetAccountBalanceResponse value) {
        return new JAXBElement<GetAccountBalanceResponse>(_GetAccountBalanceResponse_QNAME, GetAccountBalanceResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetUserDetailsResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link GetUserDetailsResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://vma.PHilae/", name = "getUserDetailsResponse")
    public JAXBElement<GetUserDetailsResponse> createGetUserDetailsResponse(GetUserDetailsResponse value) {
        return new JAXBElement<GetUserDetailsResponse>(_GetUserDetailsResponse_QNAME, GetUserDetailsResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link QueryDepositAccountResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link QueryDepositAccountResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://vma.PHilae/", name = "queryDepositAccountResponse")
    public JAXBElement<QueryDepositAccountResponse> createQueryDepositAccountResponse(QueryDepositAccountResponse value) {
        return new JAXBElement<QueryDepositAccountResponse>(_QueryDepositAccountResponse_QNAME, QueryDepositAccountResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetCustomerInfoDetails }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link GetCustomerInfoDetails }{@code >}
     */
    @XmlElementDecl(namespace = "http://vma.PHilae/", name = "getCustomerInfoDetails")
    public JAXBElement<GetCustomerInfoDetails> createGetCustomerInfoDetails(GetCustomerInfoDetails value) {
        return new JAXBElement<GetCustomerInfoDetails>(_GetCustomerInfoDetails_QNAME, GetCustomerInfoDetails.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PostDepositToGLTransferResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link PostDepositToGLTransferResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://vma.PHilae/", name = "postDepositToGLTransferResponse")
    public JAXBElement<PostDepositToGLTransferResponse> createPostDepositToGLTransferResponse(PostDepositToGLTransferResponse value) {
        return new JAXBElement<PostDepositToGLTransferResponse>(_PostDepositToGLTransferResponse_QNAME, PostDepositToGLTransferResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetBranchInfo }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link GetBranchInfo }{@code >}
     */
    @XmlElementDecl(namespace = "http://vma.PHilae/", name = "getBranchInfo")
    public JAXBElement<GetBranchInfo> createGetBranchInfo(GetBranchInfo value) {
        return new JAXBElement<GetBranchInfo>(_GetBranchInfo_QNAME, GetBranchInfo.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetCustomerAccountInfoDetailsResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link GetCustomerAccountInfoDetailsResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://vma.PHilae/", name = "getCustomerAccountInfoDetailsResponse")
    public JAXBElement<GetCustomerAccountInfoDetailsResponse> createGetCustomerAccountInfoDetailsResponse(GetCustomerAccountInfoDetailsResponse value) {
        return new JAXBElement<GetCustomerAccountInfoDetailsResponse>(_GetCustomerAccountInfoDetailsResponse_QNAME, GetCustomerAccountInfoDetailsResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PostGLToDepositTransferResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link PostGLToDepositTransferResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://vma.PHilae/", name = "postGLToDepositTransferResponse")
    public JAXBElement<PostGLToDepositTransferResponse> createPostGLToDepositTransferResponse(PostGLToDepositTransferResponse value) {
        return new JAXBElement<PostGLToDepositTransferResponse>(_PostGLToDepositTransferResponse_QNAME, PostGLToDepositTransferResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ValidateUserResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ValidateUserResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://vma.PHilae/", name = "validateUserResponse")
    public JAXBElement<ValidateUserResponse> createValidateUserResponse(ValidateUserResponse value) {
        return new JAXBElement<ValidateUserResponse>(_ValidateUserResponse_QNAME, ValidateUserResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetCustomerAccountInfoBasicResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link GetCustomerAccountInfoBasicResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://vma.PHilae/", name = "getCustomerAccountInfoBasicResponse")
    public JAXBElement<GetCustomerAccountInfoBasicResponse> createGetCustomerAccountInfoBasicResponse(GetCustomerAccountInfoBasicResponse value) {
        return new JAXBElement<GetCustomerAccountInfoBasicResponse>(_GetCustomerAccountInfoBasicResponse_QNAME, GetCustomerAccountInfoBasicResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SearchCustomer }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link SearchCustomer }{@code >}
     */
    @XmlElementDecl(namespace = "http://vma.PHilae/", name = "searchCustomer")
    public JAXBElement<SearchCustomer> createSearchCustomer(SearchCustomer value) {
        return new JAXBElement<SearchCustomer>(_SearchCustomer_QNAME, SearchCustomer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetLoanScheduleInfo }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link GetLoanScheduleInfo }{@code >}
     */
    @XmlElementDecl(namespace = "http://vma.PHilae/", name = "getLoanScheduleInfo")
    public JAXBElement<GetLoanScheduleInfo> createGetLoanScheduleInfo(GetLoanScheduleInfo value) {
        return new JAXBElement<GetLoanScheduleInfo>(_GetLoanScheduleInfo_QNAME, GetLoanScheduleInfo.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link QueryLoanInformationResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link QueryLoanInformationResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://vma.PHilae/", name = "queryLoanInformationResponse")
    public JAXBElement<QueryLoanInformationResponse> createQueryLoanInformationResponse(QueryLoanInformationResponse value) {
        return new JAXBElement<QueryLoanInformationResponse>(_QueryLoanInformationResponse_QNAME, QueryLoanInformationResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PostDepositTransfer }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link PostDepositTransfer }{@code >}
     */
    @XmlElementDecl(namespace = "http://vma.PHilae/", name = "postDepositTransfer")
    public JAXBElement<PostDepositTransfer> createPostDepositTransfer(PostDepositTransfer value) {
        return new JAXBElement<PostDepositTransfer>(_PostDepositTransfer_QNAME, PostDepositTransfer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link QueryCustomer }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link QueryCustomer }{@code >}
     */
    @XmlElementDecl(namespace = "http://vma.PHilae/", name = "queryCustomer")
    public JAXBElement<QueryCustomer> createQueryCustomer(QueryCustomer value) {
        return new JAXBElement<QueryCustomer>(_QueryCustomer_QNAME, QueryCustomer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ActivateCustomerResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ActivateCustomerResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://vma.PHilae/", name = "activateCustomerResponse")
    public JAXBElement<ActivateCustomerResponse> createActivateCustomerResponse(ActivateCustomerResponse value) {
        return new JAXBElement<ActivateCustomerResponse>(_ActivateCustomerResponse_QNAME, ActivateCustomerResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetCustomerInfoBasic }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link GetCustomerInfoBasic }{@code >}
     */
    @XmlElementDecl(namespace = "http://vma.PHilae/", name = "getCustomerInfoBasic")
    public JAXBElement<GetCustomerInfoBasic> createGetCustomerInfoBasic(GetCustomerInfoBasic value) {
        return new JAXBElement<GetCustomerInfoBasic>(_GetCustomerInfoBasic_QNAME, GetCustomerInfoBasic.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetBranchInfoResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link GetBranchInfoResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://vma.PHilae/", name = "getBranchInfoResponse")
    public JAXBElement<GetBranchInfoResponse> createGetBranchInfoResponse(GetBranchInfoResponse value) {
        return new JAXBElement<GetBranchInfoResponse>(_GetBranchInfoResponse_QNAME, GetBranchInfoResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PostDepositTransferResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link PostDepositTransferResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://vma.PHilae/", name = "postDepositTransferResponse")
    public JAXBElement<PostDepositTransferResponse> createPostDepositTransferResponse(PostDepositTransferResponse value) {
        return new JAXBElement<PostDepositTransferResponse>(_PostDepositTransferResponse_QNAME, PostDepositTransferResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link QueryBranches }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link QueryBranches }{@code >}
     */
    @XmlElementDecl(namespace = "http://vma.PHilae/", name = "queryBranches")
    public JAXBElement<QueryBranches> createQueryBranches(QueryBranches value) {
        return new JAXBElement<QueryBranches>(_QueryBranches_QNAME, QueryBranches.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetInterestRate }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link GetInterestRate }{@code >}
     */
    @XmlElementDecl(namespace = "http://vma.PHilae/", name = "getInterestRate")
    public JAXBElement<GetInterestRate> createGetInterestRate(GetInterestRate value) {
        return new JAXBElement<GetInterestRate>(_GetInterestRate_QNAME, GetInterestRate.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link QueryGLHistory }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link QueryGLHistory }{@code >}
     */
    @XmlElementDecl(namespace = "http://vma.PHilae/", name = "queryGLHistory")
    public JAXBElement<QueryGLHistory> createQueryGLHistory(QueryGLHistory value) {
        return new JAXBElement<QueryGLHistory>(_QueryGLHistory_QNAME, QueryGLHistory.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SearchTransactionDetailsResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link SearchTransactionDetailsResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://vma.PHilae/", name = "searchTransactionDetailsResponse")
    public JAXBElement<SearchTransactionDetailsResponse> createSearchTransactionDetailsResponse(SearchTransactionDetailsResponse value) {
        return new JAXBElement<SearchTransactionDetailsResponse>(_SearchTransactionDetailsResponse_QNAME, SearchTransactionDetailsResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetForeignExchangeRateResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link GetForeignExchangeRateResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://vma.PHilae/", name = "getForeignExchangeRateResponse")
    public JAXBElement<GetForeignExchangeRateResponse> createGetForeignExchangeRateResponse(GetForeignExchangeRateResponse value) {
        return new JAXBElement<GetForeignExchangeRateResponse>(_GetForeignExchangeRateResponse_QNAME, GetForeignExchangeRateResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link QueryDepositAccount }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link QueryDepositAccount }{@code >}
     */
    @XmlElementDecl(namespace = "http://vma.PHilae/", name = "queryDepositAccount")
    public JAXBElement<QueryDepositAccount> createQueryDepositAccount(QueryDepositAccount value) {
        return new JAXBElement<QueryDepositAccount>(_QueryDepositAccount_QNAME, QueryDepositAccount.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link QueryDepositHistoryResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link QueryDepositHistoryResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://vma.PHilae/", name = "queryDepositHistoryResponse")
    public JAXBElement<QueryDepositHistoryResponse> createQueryDepositHistoryResponse(QueryDepositHistoryResponse value) {
        return new JAXBElement<QueryDepositHistoryResponse>(_QueryDepositHistoryResponse_QNAME, QueryDepositHistoryResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link QueryDepositBalanceResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link QueryDepositBalanceResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://vma.PHilae/", name = "queryDepositBalanceResponse")
    public JAXBElement<QueryDepositBalanceResponse> createQueryDepositBalanceResponse(QueryDepositBalanceResponse value) {
        return new JAXBElement<QueryDepositBalanceResponse>(_QueryDepositBalanceResponse_QNAME, QueryDepositBalanceResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetAccountHistory }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link GetAccountHistory }{@code >}
     */
    @XmlElementDecl(namespace = "http://vma.PHilae/", name = "getAccountHistory")
    public JAXBElement<GetAccountHistory> createGetAccountHistory(GetAccountHistory value) {
        return new JAXBElement<GetAccountHistory>(_GetAccountHistory_QNAME, GetAccountHistory.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CreateDepositAccountResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link CreateDepositAccountResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://vma.PHilae/", name = "createDepositAccountResponse")
    public JAXBElement<CreateDepositAccountResponse> createCreateDepositAccountResponse(CreateDepositAccountResponse value) {
        return new JAXBElement<CreateDepositAccountResponse>(_CreateDepositAccountResponse_QNAME, CreateDepositAccountResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link QueryLoanSchedule }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link QueryLoanSchedule }{@code >}
     */
    @XmlElementDecl(namespace = "http://vma.PHilae/", name = "queryLoanSchedule")
    public JAXBElement<QueryLoanSchedule> createQueryLoanSchedule(QueryLoanSchedule value) {
        return new JAXBElement<QueryLoanSchedule>(_QueryLoanSchedule_QNAME, QueryLoanSchedule.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetCustomerAccountInfoDetails }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link GetCustomerAccountInfoDetails }{@code >}
     */
    @XmlElementDecl(namespace = "http://vma.PHilae/", name = "getCustomerAccountInfoDetails")
    public JAXBElement<GetCustomerAccountInfoDetails> createGetCustomerAccountInfoDetails(GetCustomerAccountInfoDetails value) {
        return new JAXBElement<GetCustomerAccountInfoDetails>(_GetCustomerAccountInfoDetails_QNAME, GetCustomerAccountInfoDetails.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetAccountBalance }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link GetAccountBalance }{@code >}
     */
    @XmlElementDecl(namespace = "http://vma.PHilae/", name = "getAccountBalance")
    public JAXBElement<GetAccountBalance> createGetAccountBalance(GetAccountBalance value) {
        return new JAXBElement<GetAccountBalance>(_GetAccountBalance_QNAME, GetAccountBalance.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link QueryLoanInformation }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link QueryLoanInformation }{@code >}
     */
    @XmlElementDecl(namespace = "http://vma.PHilae/", name = "queryLoanInformation")
    public JAXBElement<QueryLoanInformation> createQueryLoanInformation(QueryLoanInformation value) {
        return new JAXBElement<QueryLoanInformation>(_QueryLoanInformation_QNAME, QueryLoanInformation.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PostGLToDepositTransfer }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link PostGLToDepositTransfer }{@code >}
     */
    @XmlElementDecl(namespace = "http://vma.PHilae/", name = "postGLToDepositTransfer")
    public JAXBElement<PostGLToDepositTransfer> createPostGLToDepositTransfer(PostGLToDepositTransfer value) {
        return new JAXBElement<PostGLToDepositTransfer>(_PostGLToDepositTransfer_QNAME, PostGLToDepositTransfer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetAccountHistoryResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link GetAccountHistoryResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://vma.PHilae/", name = "getAccountHistoryResponse")
    public JAXBElement<GetAccountHistoryResponse> createGetAccountHistoryResponse(GetAccountHistoryResponse value) {
        return new JAXBElement<GetAccountHistoryResponse>(_GetAccountHistoryResponse_QNAME, GetAccountHistoryResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetLoanInfo }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link GetLoanInfo }{@code >}
     */
    @XmlElementDecl(namespace = "http://vma.PHilae/", name = "getLoanInfo")
    public JAXBElement<GetLoanInfo> createGetLoanInfo(GetLoanInfo value) {
        return new JAXBElement<GetLoanInfo>(_GetLoanInfo_QNAME, GetLoanInfo.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ActivateCustomer }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ActivateCustomer }{@code >}
     */
    @XmlElementDecl(namespace = "http://vma.PHilae/", name = "activateCustomer")
    public JAXBElement<ActivateCustomer> createActivateCustomer(ActivateCustomer value) {
        return new JAXBElement<ActivateCustomer>(_ActivateCustomer_QNAME, ActivateCustomer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PostGLToGLTransferResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link PostGLToGLTransferResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://vma.PHilae/", name = "postGLToGLTransferResponse")
    public JAXBElement<PostGLToGLTransferResponse> createPostGLToGLTransferResponse(PostGLToGLTransferResponse value) {
        return new JAXBElement<PostGLToGLTransferResponse>(_PostGLToGLTransferResponse_QNAME, PostGLToGLTransferResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link QueryDepositMinistatementResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link QueryDepositMinistatementResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://vma.PHilae/", name = "queryDepositMinistatementResponse")
    public JAXBElement<QueryDepositMinistatementResponse> createQueryDepositMinistatementResponse(QueryDepositMinistatementResponse value) {
        return new JAXBElement<QueryDepositMinistatementResponse>(_QueryDepositMinistatementResponse_QNAME, QueryDepositMinistatementResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ActivateDepositAccountResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ActivateDepositAccountResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://vma.PHilae/", name = "activateDepositAccountResponse")
    public JAXBElement<ActivateDepositAccountResponse> createActivateDepositAccountResponse(ActivateDepositAccountResponse value) {
        return new JAXBElement<ActivateDepositAccountResponse>(_ActivateDepositAccountResponse_QNAME, ActivateDepositAccountResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetLoanInfoResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link GetLoanInfoResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://vma.PHilae/", name = "getLoanInfoResponse")
    public JAXBElement<GetLoanInfoResponse> createGetLoanInfoResponse(GetLoanInfoResponse value) {
        return new JAXBElement<GetLoanInfoResponse>(_GetLoanInfoResponse_QNAME, GetLoanInfoResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link QueryGLHistoryResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link QueryGLHistoryResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://vma.PHilae/", name = "queryGLHistoryResponse")
    public JAXBElement<QueryGLHistoryResponse> createQueryGLHistoryResponse(QueryGLHistoryResponse value) {
        return new JAXBElement<QueryGLHistoryResponse>(_QueryGLHistoryResponse_QNAME, QueryGLHistoryResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CreateDepositAccount }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link CreateDepositAccount }{@code >}
     */
    @XmlElementDecl(namespace = "http://vma.PHilae/", name = "createDepositAccount")
    public JAXBElement<CreateDepositAccount> createCreateDepositAccount(CreateDepositAccount value) {
        return new JAXBElement<CreateDepositAccount>(_CreateDepositAccount_QNAME, CreateDepositAccount.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SearchCustomerInBranchResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link SearchCustomerInBranchResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://vma.PHilae/", name = "searchCustomerInBranchResponse")
    public JAXBElement<SearchCustomerInBranchResponse> createSearchCustomerInBranchResponse(SearchCustomerInBranchResponse value) {
        return new JAXBElement<SearchCustomerInBranchResponse>(_SearchCustomerInBranchResponse_QNAME, SearchCustomerInBranchResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link QueryDepositBalance }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link QueryDepositBalance }{@code >}
     */
    @XmlElementDecl(namespace = "http://vma.PHilae/", name = "queryDepositBalance")
    public JAXBElement<QueryDepositBalance> createQueryDepositBalance(QueryDepositBalance value) {
        return new JAXBElement<QueryDepositBalance>(_QueryDepositBalance_QNAME, QueryDepositBalance.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link QueryDepositHistory }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link QueryDepositHistory }{@code >}
     */
    @XmlElementDecl(namespace = "http://vma.PHilae/", name = "queryDepositHistory")
    public JAXBElement<QueryDepositHistory> createQueryDepositHistory(QueryDepositHistory value) {
        return new JAXBElement<QueryDepositHistory>(_QueryDepositHistory_QNAME, QueryDepositHistory.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ValidateTransaction }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ValidateTransaction }{@code >}
     */
    @XmlElementDecl(namespace = "http://vma.PHilae/", name = "validateTransaction")
    public JAXBElement<ValidateTransaction> createValidateTransaction(ValidateTransaction value) {
        return new JAXBElement<ValidateTransaction>(_ValidateTransaction_QNAME, ValidateTransaction.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CreateCustomer }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link CreateCustomer }{@code >}
     */
    @XmlElementDecl(namespace = "http://vma.PHilae/", name = "createCustomer")
    public JAXBElement<CreateCustomer> createCreateCustomer(CreateCustomer value) {
        return new JAXBElement<CreateCustomer>(_CreateCustomer_QNAME, CreateCustomer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetCustomerInfoDetailsResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link GetCustomerInfoDetailsResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://vma.PHilae/", name = "getCustomerInfoDetailsResponse")
    public JAXBElement<GetCustomerInfoDetailsResponse> createGetCustomerInfoDetailsResponse(GetCustomerInfoDetailsResponse value) {
        return new JAXBElement<GetCustomerInfoDetailsResponse>(_GetCustomerInfoDetailsResponse_QNAME, GetCustomerInfoDetailsResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link QueryBranchesResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link QueryBranchesResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://vma.PHilae/", name = "queryBranchesResponse")
    public JAXBElement<QueryBranchesResponse> createQueryBranchesResponse(QueryBranchesResponse value) {
        return new JAXBElement<QueryBranchesResponse>(_QueryBranchesResponse_QNAME, QueryBranchesResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CreateCustomerResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link CreateCustomerResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://vma.PHilae/", name = "createCustomerResponse")
    public JAXBElement<CreateCustomerResponse> createCreateCustomerResponse(CreateCustomerResponse value) {
        return new JAXBElement<CreateCustomerResponse>(_CreateCustomerResponse_QNAME, CreateCustomerResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SearchTransactionDetails }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link SearchTransactionDetails }{@code >}
     */
    @XmlElementDecl(namespace = "http://vma.PHilae/", name = "searchTransactionDetails")
    public JAXBElement<SearchTransactionDetails> createSearchTransactionDetails(SearchTransactionDetails value) {
        return new JAXBElement<SearchTransactionDetails>(_SearchTransactionDetails_QNAME, SearchTransactionDetails.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetCustomerAccountInfoBasic }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link GetCustomerAccountInfoBasic }{@code >}
     */
    @XmlElementDecl(namespace = "http://vma.PHilae/", name = "getCustomerAccountInfoBasic")
    public JAXBElement<GetCustomerAccountInfoBasic> createGetCustomerAccountInfoBasic(GetCustomerAccountInfoBasic value) {
        return new JAXBElement<GetCustomerAccountInfoBasic>(_GetCustomerAccountInfoBasic_QNAME, GetCustomerAccountInfoBasic.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link QueryDepositMinistatement }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link QueryDepositMinistatement }{@code >}
     */
    @XmlElementDecl(namespace = "http://vma.PHilae/", name = "queryDepositMinistatement")
    public JAXBElement<QueryDepositMinistatement> createQueryDepositMinistatement(QueryDepositMinistatement value) {
        return new JAXBElement<QueryDepositMinistatement>(_QueryDepositMinistatement_QNAME, QueryDepositMinistatement.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ActivateDepositAccount }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ActivateDepositAccount }{@code >}
     */
    @XmlElementDecl(namespace = "http://vma.PHilae/", name = "activateDepositAccount")
    public JAXBElement<ActivateDepositAccount> createActivateDepositAccount(ActivateDepositAccount value) {
        return new JAXBElement<ActivateDepositAccount>(_ActivateDepositAccount_QNAME, ActivateDepositAccount.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SearchCustomerResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link SearchCustomerResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://vma.PHilae/", name = "searchCustomerResponse")
    public JAXBElement<SearchCustomerResponse> createSearchCustomerResponse(SearchCustomerResponse value) {
        return new JAXBElement<SearchCustomerResponse>(_SearchCustomerResponse_QNAME, SearchCustomerResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetCustomerInfoBasicResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link GetCustomerInfoBasicResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://vma.PHilae/", name = "getCustomerInfoBasicResponse")
    public JAXBElement<GetCustomerInfoBasicResponse> createGetCustomerInfoBasicResponse(GetCustomerInfoBasicResponse value) {
        return new JAXBElement<GetCustomerInfoBasicResponse>(_GetCustomerInfoBasicResponse_QNAME, GetCustomerInfoBasicResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetInterestRateResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link GetInterestRateResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://vma.PHilae/", name = "getInterestRateResponse")
    public JAXBElement<GetInterestRateResponse> createGetInterestRateResponse(GetInterestRateResponse value) {
        return new JAXBElement<GetInterestRateResponse>(_GetInterestRateResponse_QNAME, GetInterestRateResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetForeignExchangeRate }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link GetForeignExchangeRate }{@code >}
     */
    @XmlElementDecl(namespace = "http://vma.PHilae/", name = "getForeignExchangeRate")
    public JAXBElement<GetForeignExchangeRate> createGetForeignExchangeRate(GetForeignExchangeRate value) {
        return new JAXBElement<GetForeignExchangeRate>(_GetForeignExchangeRate_QNAME, GetForeignExchangeRate.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetUserDetails }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link GetUserDetails }{@code >}
     */
    @XmlElementDecl(namespace = "http://vma.PHilae/", name = "getUserDetails")
    public JAXBElement<GetUserDetails> createGetUserDetails(GetUserDetails value) {
        return new JAXBElement<GetUserDetails>(_GetUserDetails_QNAME, GetUserDetails.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PostDepositToGLTransfer }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link PostDepositToGLTransfer }{@code >}
     */
    @XmlElementDecl(namespace = "http://vma.PHilae/", name = "postDepositToGLTransfer")
    public JAXBElement<PostDepositToGLTransfer> createPostDepositToGLTransfer(PostDepositToGLTransfer value) {
        return new JAXBElement<PostDepositToGLTransfer>(_PostDepositToGLTransfer_QNAME, PostDepositToGLTransfer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link QueryCustomerResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link QueryCustomerResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://vma.PHilae/", name = "queryCustomerResponse")
    public JAXBElement<QueryCustomerResponse> createQueryCustomerResponse(QueryCustomerResponse value) {
        return new JAXBElement<QueryCustomerResponse>(_QueryCustomerResponse_QNAME, QueryCustomerResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ValidateTransactionResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ValidateTransactionResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://vma.PHilae/", name = "validateTransactionResponse")
    public JAXBElement<ValidateTransactionResponse> createValidateTransactionResponse(ValidateTransactionResponse value) {
        return new JAXBElement<ValidateTransactionResponse>(_ValidateTransactionResponse_QNAME, ValidateTransactionResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ValidateUser }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ValidateUser }{@code >}
     */
    @XmlElementDecl(namespace = "http://vma.PHilae/", name = "validateUser")
    public JAXBElement<ValidateUser> createValidateUser(ValidateUser value) {
        return new JAXBElement<ValidateUser>(_ValidateUser_QNAME, ValidateUser.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link QueryLoanScheduleResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link QueryLoanScheduleResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://vma.PHilae/", name = "queryLoanScheduleResponse")
    public JAXBElement<QueryLoanScheduleResponse> createQueryLoanScheduleResponse(QueryLoanScheduleResponse value) {
        return new JAXBElement<QueryLoanScheduleResponse>(_QueryLoanScheduleResponse_QNAME, QueryLoanScheduleResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PostGLToGLTransfer }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link PostGLToGLTransfer }{@code >}
     */
    @XmlElementDecl(namespace = "http://vma.PHilae/", name = "postGLToGLTransfer")
    public JAXBElement<PostGLToGLTransfer> createPostGLToGLTransfer(PostGLToGLTransfer value) {
        return new JAXBElement<PostGLToGLTransfer>(_PostGLToGLTransfer_QNAME, PostGLToGLTransfer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetAccountInformation }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link GetAccountInformation }{@code >}
     */
    @XmlElementDecl(namespace = "http://vma.PHilae/", name = "getAccountInformation")
    public JAXBElement<GetAccountInformation> createGetAccountInformation(GetAccountInformation value) {
        return new JAXBElement<GetAccountInformation>(_GetAccountInformation_QNAME, GetAccountInformation.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SearchCustomerInBranch }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link SearchCustomerInBranch }{@code >}
     */
    @XmlElementDecl(namespace = "http://vma.PHilae/", name = "searchCustomerInBranch")
    public JAXBElement<SearchCustomerInBranch> createSearchCustomerInBranch(SearchCustomerInBranch value) {
        return new JAXBElement<SearchCustomerInBranch>(_SearchCustomerInBranch_QNAME, SearchCustomerInBranch.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetLoanScheduleInfoResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link GetLoanScheduleInfoResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://vma.PHilae/", name = "getLoanScheduleInfoResponse")
    public JAXBElement<GetLoanScheduleInfoResponse> createGetLoanScheduleInfoResponse(GetLoanScheduleInfoResponse value) {
        return new JAXBElement<GetLoanScheduleInfoResponse>(_GetLoanScheduleInfoResponse_QNAME, GetLoanScheduleInfoResponse.class, null, value);
    }

}
