
server:
  port: 8050
  error:
    include-message: always

spring:
  profiles:
    active: test
  application:
    name: e-murabaha-service
  datasource:
    url: jdbc:sqlserver://172.16.1.17:1433;databaseName=digital_loan;encrypt=true;trustServerCertificate=true;andtrustServerCertificate=false
    username: sa
    password: Today1234
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    database-platform: org.hibernate.dialect.SQLServer2012Dialect
    show-sql: true
  main:
    allow-circular-references: true

sahay:
  endpoint: http://172.16.1.17:8013/channel/request
  sms-endpoint: http://172.16.3.24:7088/api/v1/request
  sp-caller: http://172.16.3.25:8064/sp/api/v1/request
  sms-to-success-template-id: 166
  sms-to-failure-template-id: 145
  sms-from-success-template-id: 165
  sms-from-failure-template-id: 147

cbs:
  endpoint: http://172.16.2.11:3900/philae/xws/vma
  username: VMA
  password: vm@pi#81*

logging:
  pattern:
    file: '%date| %-5level | %-30thread | e-murabaha-service | %-30.30logger{0} -%line
      |%msg%n'
    console: '%date| %highlight(%-5level) | %magenta(%-30thread) | e-murabaha-service
      | %-30.30logger{0} -%line |%msg%n'

  file:
    path: E:\Apps\e-murabaha-service\logs
    name: ${logging.file.path}/e-murabaha-service.log
async:
  thread:
    queue:
      capacity:
        size: 500
    core:
      pool:
        size: 2
    max:
      pool:
        size: 5
    name:
      prefix: e-murabaha-async
